mail:
  sendgrid:
    apiKey: apikey
    fromEmail: email
    senderName: name

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/email_db?createDatabaseIfNotExist=true&useSSL=false
    username: root
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true